platform :ios, '9.0'

target 'GithubManager' do
pod 'AFNetworking', '~> 3.0'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for GithubManager

end
